spring:
  application:
    name: meeting_project

  datasource:
    url: jdbc:mysql://localhost:3306/meeting_system
    username: chill
    password: chill
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # 테이블 자동 생성
    show-sql: true  # SQL 실행 로그 출력
    properties:
      hibernate:
        format_sql: true


